# Generated by Django 5.2.8 on 2025-11-20 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegiaoAfetada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_identificacao', models.CharField(help_text='Ex: Bairro Centro - Enchente 2024', max_length=100)),
                ('cep', models.CharField(help_text="CEP no formato apenas com números Ex.: '83060-035' -> '83060035'", max_length=8)),
                ('estado', models.CharField(help_text='Ex: PR, SP, RJ, BA', max_length=2)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=100, verbose_name='Rua/Logradouro')),
                ('tipo_desastre', models.CharField(help_text='Ex: Alagamento, Deslizamento, Incêndio', max_length=100)),
                ('nivel_prioridade', models.IntegerField(choices=[(1, 'Baixa - Monitoramento'), (2, 'Média - Danos Materiais'), (3, 'Alta - Desabrigados'), (4, 'Crítica - Risco de Vida / Calamidade Pública')], default=1)),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Ajuda'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('CONCLUIDO', 'Situação Estabilizada')], default='AGUARDANDO', max_length=20)),
                ('necessidades_imediatas', models.TextField(help_text='O que é mais urgente? Água? Barcos? Médicos?')),
                ('data_ocorrencia', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-nivel_prioridade', 'data_ocorrencia'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('produto', models.CharField(help_text='Ex: Garrafas de 1.5L, Arroz 5kg', max_length=100)),
                ('tipo', models.CharField(choices=[('AGUA', 'Água Potável'), ('ALIMENTO', 'Alimento Não Perecível'), ('ROUPA', 'Vestuário/Cama/Banho'), ('HIGIENE', 'Itens de Higiene'), ('MEDICAMENTO', 'Medicamentos'), ('DINHEIRO', 'Aporte Financeiro'), ('MATERIAL', 'Material para reforma'), ('OUTRO', 'Outros')], default='OUTRO', max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('unidade_medida', models.CharField(blank=True, help_text='Ex: Litros, Kg, Unidades, Caixas', max_length=20, null=True)),
                ('quantidade_por_volume', models.PositiveIntegerField(default=0)),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível / Em Estoque'), ('RESERVADO', 'Reservado para Região'), ('EM_TRANSITO', 'Em Trânsito / Saiu para Entrega'), ('ENTREGUE', 'Entregue ao Destino')], default='DISPONIVEL', max_length=20)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
                ('entregue', models.BooleanField(default=False, verbose_name='Foi entregue ao destino?')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurso_enviado', to='app.regiaoafetada', verbose_name='Região Destino')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(help_text='Celular ou telefone de contato', max_length=9)),
                ('ddd', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('habilidade_principal', models.CharField(choices=[('SAUDE', 'Profissional de Saúde (Médico/Enfermeiro)'), ('RESGATE', 'Busca e Resgate'), ('LOGISTICA', 'Logística e Transporte'), ('PSICO', 'Apoio Psicológico'), ('GERAL', 'Serviços Gerais / Limpeza'), ('COZINHA', 'Cozinha e Alimentação')], default='GERAL', max_length=20)),
                ('disponibilidade', models.CharField(choices=[('MANHA', 'Manhã (08:00 - 12:00)'), ('TARDE', 'Tarde (13:00 - 18:00)'), ('NOITE', 'Noite (19:00 - 22:00)'), ('MADRUGADA', 'Madrugada (22:00 - 08:00)'), ('FIM_SEMANA', 'Finais de Semana'), ('TOTAL', 'Disponibilidade Total'), ('VARIAVEL', 'Horário Variável / A combinar')], default='VARIAVEL', help_text='Período principal de disponibilidade', max_length=20)),
                ('regiao_afetada_atuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regiao_atuacao', to='app.regiaoafetada', verbose_name='Região Destino')),
            ],
        ),
    ]
